from backend.errors.chat_exceptions import (
    ChatNotFound,
    ChatMessageNotFound,
    InvalidChatPrompt,
    InvalidChatMessageStatus,
)
from backend.errors.config_exceptions import (
    InvalidSourceTable,
    InvalidDestinationTable,
    InvalidMaterialization,
    ReferenceNotFound,
    InvalidModelConfigError,
)
from backend.errors.dependency_exceptions import ColumnDependency, ModelDependency, TransformationDependency, ProjectDependencyException, \
    MultipleColumnDependency, ModelTableDependency
from backend.errors.exceptions import (
    UnhandledErrorMessage,
    VisitranCoreExceptions,
    ProjectNotExist,
    ProjectAlreadyExists,
    ConnectionAlreadyExists,
    ConnectionNotExists,
    ConnectionDependencyError,
    ModelAlreadyExists,
    ModelNotExists,
    CSVFileAlreadyExists,
    CSVFileNotExists,
    InvalidUserException,
    BackupNotExistException,
    EnvironmentNotExists,
    EnvironmentAlreadyExist,
    SampleProjectConnectionFailed,
    ResourcePermissionDeniedException,
    TableContentIssue,
    LLMModelFailure,
    MasterDbNotExist,
    SchemaMissingInSeedUpload,
    CsvDownloadFailed,
    SchemaNotFoundError, AIRaisedException,
)
from backend.errors.validation_exceptions import (
    DestinationTableAlreadyExist,
    SourceTableDoesNotExist,
    JoinTableDoesNotExist,
    MergeTableDoesNotExist,
    CircularDependencyReference,
    InvalidSQLQuery,
    SQLExtractionError,
    ProhibitedSqlQuery,
)

__all__ = [
    "UnhandledErrorMessage",
    "VisitranCoreExceptions",
    "ProjectNotExist",
    "ProjectAlreadyExists",
    "ConnectionAlreadyExists",
    "ConnectionNotExists",
    "ConnectionDependencyError",
    "ModelAlreadyExists",
    "ModelNotExists",
    "CSVFileAlreadyExists",
    "CSVFileNotExists",
    "BackupNotExistException",
    "EnvironmentNotExists",
    "EnvironmentAlreadyExist",
    "SampleProjectConnectionFailed",
    # Permission based exceptions
    "ResourcePermissionDeniedException",
    "InvalidUserException",
    # Validation based exceptions
    "DestinationTableAlreadyExist",
    "SourceTableDoesNotExist",
    "JoinTableDoesNotExist",
    "MergeTableDoesNotExist",
    "CircularDependencyReference",
    "ModelDependency",
    "InvalidSQLQuery",
    "SQLExtractionError",
    "ProhibitedSqlQuery",
    "MasterDbNotExist",
    # Dependency validation exception from config models
    "ModelTableDependency",
    "ColumnDependency",
    "MultipleColumnDependency",
    "TransformationDependency",
    # Ai Chat exceptions
    "ChatNotFound",
    "ChatMessageNotFound",
    "InvalidChatPrompt",
    "InvalidChatMessageStatus",
    "LLMModelFailure",
    "AIRaisedException",
    # Yaml configuration validations
    "InvalidSourceTable",
    "InvalidDestinationTable",
    "InvalidMaterialization",
    "ReferenceNotFound",
    "InvalidModelConfigError",
    "TableContentIssue",
    "SchemaMissingInSeedUpload",
    "CsvDownloadFailed",
    "SchemaNotFoundError",
    "ProjectDependencyException"
]
