from backend.errors.chat_exceptions import (
    ChatMessageNotFound,
    ChatNotFound,
    InvalidChatMessageStatus,
    InvalidChatPrompt,
)
from backend.errors.config_exceptions import (
    InvalidDestinationTable,
    InvalidMaterialization,
    InvalidModelConfigError,
    InvalidSourceTable,
    ReferenceNotFound,
)
from backend.errors.dependency_exceptions import (
    ColumnDependency,
    ModelDependency,
    ModelTableDependency,
    MultipleColumnDependency,
    ProjectDependencyException,
    TransformationDependency,
)
from backend.errors.exceptions import (
    AIRaisedException,
    BackupNotExistException,
    ConnectionAlreadyExists,
    ConnectionDependencyError,
    ConnectionNotExists,
    CsvDownloadFailed,
    CSVFileAlreadyExists,
    CSVFileNotExists,
    EnvironmentAlreadyExist,
    EnvironmentNotExists,
    InvalidUserException,
    LLMModelFailure,
    MasterDbNotExist,
    ModelAlreadyExists,
    ModelNotExists,
    ProjectAlreadyExists,
    ProjectNotExist,
    ResourcePermissionDeniedException,
    SampleProjectConnectionFailed,
    SchemaMissingInSeedUpload,
    SchemaNotFoundError,
    TableContentIssue,
    UnhandledErrorMessage,
    VisitranCoreExceptions,
)
from backend.errors.validation_exceptions import (
    CircularDependencyReference,
    DestinationTableAlreadyExist,
    InvalidSQLQuery,
    JoinTableDoesNotExist,
    MergeTableDoesNotExist,
    ProhibitedSqlQuery,
    SourceTableDoesNotExist,
    SQLExtractionError,
)

__all__ = [
    "UnhandledErrorMessage",
    "VisitranCoreExceptions",
    "ProjectNotExist",
    "ProjectAlreadyExists",
    "ConnectionAlreadyExists",
    "ConnectionNotExists",
    "ConnectionDependencyError",
    "ModelAlreadyExists",
    "ModelNotExists",
    "CSVFileAlreadyExists",
    "CSVFileNotExists",
    "BackupNotExistException",
    "EnvironmentNotExists",
    "EnvironmentAlreadyExist",
    "SampleProjectConnectionFailed",
    # Permission based exceptions
    "ResourcePermissionDeniedException",
    "InvalidUserException",
    # Validation based exceptions
    "DestinationTableAlreadyExist",
    "SourceTableDoesNotExist",
    "JoinTableDoesNotExist",
    "MergeTableDoesNotExist",
    "CircularDependencyReference",
    "ModelDependency",
    "InvalidSQLQuery",
    "SQLExtractionError",
    "ProhibitedSqlQuery",
    "MasterDbNotExist",
    # Dependency validation exception from config models
    "ModelTableDependency",
    "ColumnDependency",
    "MultipleColumnDependency",
    "TransformationDependency",
    # Ai Chat exceptions
    "ChatNotFound",
    "ChatMessageNotFound",
    "InvalidChatPrompt",
    "InvalidChatMessageStatus",
    "LLMModelFailure",
    "AIRaisedException",
    # Yaml configuration validations
    "InvalidSourceTable",
    "InvalidDestinationTable",
    "InvalidMaterialization",
    "ReferenceNotFound",
    "InvalidModelConfigError",
    "TableContentIssue",
    "SchemaMissingInSeedUpload",
    "CsvDownloadFailed",
    "SchemaNotFoundError",
    "ProjectDependencyException",
]
