# Generated by Django 4.2.10 on 2026-03-16 06:47

import uuid
from decimal import Decimal

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import backend.core.models.config_models
import backend.core.models.csv_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("user_id", models.CharField(max_length=64)),
                ("project_storage_created", models.BooleanField(default=False)),
                ("profile_picture_url", models.TextField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="customuser_set", related_query_name="customuser", to="auth.group"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="customuser_set", related_query_name="customuser", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("chat_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("chat_name", models.CharField(help_text="Human-readable name for the chat.", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Flag for soft deletion. True means the chat is hidden."
                    ),
                ),
                (
                    "llm_model_architect",
                    models.CharField(
                        default="anthropic/claude-3-7-sonnet",
                        help_text="String identifier of the architect LLM model used for this chat.",
                        max_length=255,
                    ),
                ),
                (
                    "llm_model_developer",
                    models.CharField(
                        default="anthropic/claude-3-7-sonnet",
                        help_text="String identifier of the developer LLM model used for this chat.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatIntent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_intent_id",
                    models.UUIDField(
                        editable=False,
                        help_text="Unique identifier for this ChatIntent.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("INFO", "INFO"), ("TRANSFORM", "TRANSFORM"), ("SQL", "SQL")],
                        editable=False,
                        help_text="Internal name of the intent. Must be one of INFO, GENERATE, SQL, NOTA, AUTO.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        choices=[("Chat", "Chat"), ("Transform", "Transform"), ("SQL", "SQL")],
                        editable=False,
                        help_text="User-facing display name for the intent.",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Intent",
                "verbose_name_plural": "Chat Intents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this ChatMessage.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.CharField(help_text="Text input or question from the user.", max_length=65000)),
                (
                    "response",
                    models.JSONField(blank=True, help_text="JSON response generated for this message.", null=True),
                ),
                (
                    "technical_content",
                    models.TextField(
                        blank=True,
                        help_text="Optional field to store technical data (e.g. YAML for 'Transform' or SQL query for 'SQL'). Empty for 'Info' intent.",
                        null=True,
                    ),
                ),
                (
                    "response_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Time taken in milliseconds to generate the response."
                    ),
                ),
                (
                    "thought_chain",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of thought processes before generating the response.",
                        null=True,
                    ),
                ),
                (
                    "prompt_status",
                    models.CharField(
                        choices=[
                            ("YET_TO_START", "YET_TO_START"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                        ],
                        default="YET_TO_START",
                        help_text="Status of prompt processing.",
                        max_length=20,
                    ),
                ),
                (
                    "prompt_error_message",
                    models.JSONField(blank=True, help_text="Error message for prompt processing.", null=True),
                ),
                (
                    "transformation_type",
                    models.CharField(
                        choices=[("DISCUSSION", "DISCUSSION"), ("TRANSFORM", "TRANSFORM")],
                        default="DISCUSSION",
                        help_text="Type of transformation stage. Could be 'Discussion' or 'Transform'.",
                        max_length=50,
                    ),
                ),
                (
                    "discussion_type",
                    models.CharField(
                        choices=[
                            ("INPROGRESS", "INPROGRESS"),
                            ("APPROVED", "APPROVED"),
                            ("GENERATE", "GENERATE"),
                            ("DISAPPROVED", "DISAPPROVED"),
                        ],
                        default="INPROGRESS",
                        help_text="Marks stages within discussion flow.",
                        max_length=50,
                    ),
                ),
                (
                    "last_discussion_id",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Unique identifier for final approved discussion ChatMessage ID."
                    ),
                ),
                (
                    "transformation_status",
                    models.CharField(
                        choices=[
                            ("YET_TO_START", "YET_TO_START"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                        ],
                        default="YET_TO_START",
                        help_text="Status of transformation processing.",
                        max_length=20,
                    ),
                ),
                (
                    "generated_models",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of generated models after transformation Applied.",
                        null=True,
                    ),
                ),
                (
                    "transformation_error_message",
                    models.JSONField(blank=True, help_text="Error message for transformation processing.", null=True),
                ),
                (
                    "llm_model_architect",
                    models.CharField(
                        default="anthropic/claude-3-7-sonnet",
                        help_text="String identifier of the architect LLM model used for this chat.",
                        max_length=255,
                    ),
                ),
                (
                    "llm_model_developer",
                    models.CharField(
                        default="anthropic/claude-3-7-sonnet",
                        help_text="String identifier of the developer LLM model used for this chat.",
                        max_length=255,
                    ),
                ),
                (
                    "has_feedback",
                    models.BooleanField(
                        default=False, help_text="Indicates whether this message has received user feedback."
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        choices=[("0", "Neutral"), ("P", "Positive"), ("N", "Negative")],
                        default="0",
                        help_text="Feedback value: 0=Neutral, P=Positive, N=Negative",
                        max_length=1,
                    ),
                ),
                (
                    "feedback_timestamp",
                    models.DateTimeField(blank=True, help_text="When the feedback was provided.", null=True),
                ),
                (
                    "feedback_comment",
                    models.TextField(blank=True, help_text="Optional comment provided with feedback.", null=True),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Parent Chat to which this message belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chat",
                    ),
                ),
                (
                    "chat_intent",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Optional intent associated with this message. Cannot be edited.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="core.chatintent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this message.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigModels",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("model_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=100)),
                ("model_data", models.JSONField(default=dict)),
                (
                    "model_py_content",
                    models.FileField(
                        max_length=250, upload_to=backend.core.models.config_models.ConfigModels.get_model_upload_path
                    ),
                ),
                ("last_modified_by", models.JSONField(default=dict)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ("config_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConnectionDetails",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "connection_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("connection_name", models.CharField(max_length=100)),
                ("datasource_name", models.CharField(max_length=100)),
                ("connection_description", models.CharField(max_length=500)),
                ("connection_details", models.JSONField(default=dict)),
                ("is_connection_exist", models.BooleanField(default=True)),
                ("is_connection_valid", models.BooleanField(default=True)),
                ("shared_with", models.JSONField(default=list)),
                ("created_by", models.JSONField(default=dict)),
                ("last_modified_by", models.JSONField(default=dict)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnvironmentModels",
            fields=[
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "environment_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("environment_name", models.CharField(max_length=100, unique=True)),
                ("environment_description", models.CharField(max_length=500)),
                ("deployment_type", models.CharField(max_length=100)),
                ("env_connection_data", models.JSONField(default=dict)),
                ("env_custom_data", models.JSONField(default=dict)),
                ("is_tested", models.BooleanField(default=False)),
                ("shared_with", models.JSONField(default=list)),
                ("created_by", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_by", models.JSONField(default=dict)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "connection_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_model",
                        to="core.connectiondetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("template_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("welcome_message", models.TextField()),
                ("template_data", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_onboarding_template",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=64)),
                ("organization_id", models.CharField(max_length=64, unique=True)),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, help_text="Stripe customer ID for billing and payments", max_length=128, null=True
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_orgs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_orgs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectDetails",
            fields=[
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "project_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("project_description", models.CharField(max_length=500)),
                ("project_py_name", models.CharField(blank=True, max_length=100, null=True)),
                ("project_path", models.CharField(max_length=100)),
                ("profile_path", models.CharField(max_length=100)),
                ("project_schema", models.CharField(blank=True, max_length=20, null=True)),
                ("created_by", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_by", models.JSONField(default=dict)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("shared_with", models.JSONField(default=list)),
                ("project_model_graph", models.JSONField(default=dict)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_sample", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "onboarding_enabled",
                    models.BooleanField(db_comment="Flag to enable/disable onboarding for this project", default=False),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        db_comment="Type of project: jaffle_shop_starter, jaffle_shop_finalize, dvd_rental_starter, dvd_rental_finalizer, or null for normal projects",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "connection_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project", to="core.connectiondetails"
                    ),
                ),
                (
                    "environment_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="core.environmentmodels",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserAIContextRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("context_rules", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Context Rules",
                "verbose_name_plural": "User AI Context Rules",
                "db_table": "core_user_ai_context_rules",
            },
        ),
        migrations.CreateModel(
            name="ProjectAIContextRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("context_rules", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_ai_context_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context_rules",
                        to="core.projectdetails",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_project_ai_context_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project AI Context Rules",
                "verbose_name_plural": "Project AI Context Rules",
                "db_table": "core_project_ai_context_rules",
            },
        ),
        migrations.AddField(
            model_name="environmentmodels",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the Organization model.",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.CreateModel(
            name="DependentModels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("transformation_id", models.CharField(max_length=100)),
                ("model_data", models.JSONField(default=dict)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.configmodels")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_model",
                        to="core.projectdetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CSVModels",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("csv_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("csv_name", models.CharField(max_length=100)),
                ("csv_field", models.FileField(upload_to=backend.core.models.csv_models.CSVModels.get_csv_upload_path)),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                ("table_schema", models.CharField(blank=True, max_length=255, null=True)),
                ("upload_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("table_exists", models.BooleanField(default=False)),
                ("uploaded_by", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="csv_model", to="core.projectdetails"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="connectiondetails",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the Organization model.",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="configmodels",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the Organization model.",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="configmodels",
            name="project_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="config_model", to="core.projectdetails"
            ),
        ),
        migrations.CreateModel(
            name="ChatTokenCost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "token_cost_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this token cost record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Session identifier for grouping related requests (Channel Id often generated by org_id, project_id, chat_id and chat_message_id",
                        max_length=255,
                    ),
                ),
                ("chat_intent", models.CharField(help_text="Intent type of the chat model", max_length=255)),
                (
                    "architect_model_name",
                    models.CharField(help_text="Name of the architect LLM model used.", max_length=255),
                ),
                (
                    "architect_input_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of input tokens used by architect LLM.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "architect_output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of output tokens generated by architect LLM.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "architect_total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total tokens (input + output) used by architect LLM.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "architect_estimated_cost",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0E-8"),
                        help_text="Estimated cost in USD for architect LLM usage.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "developer_model_name",
                    models.CharField(help_text="Name of the developer LLM model used.", max_length=255),
                ),
                (
                    "developer_input_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of input tokens used by developer LLM.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "developer_output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of output tokens generated by developer LLM.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "developer_total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total tokens (input + output) used by developer LLM.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "developer_estimated_cost",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0E-8"),
                        help_text="Estimated cost in USD for developer LLM usage.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "total_input_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Combined input tokens from both LLMs.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Combined output tokens from both LLMs.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Combined total tokens from both LLMs.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0E-8"),
                        help_text="Total estimated cost in USD for both LLMs.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Time taken in milliseconds for token processing."
                    ),
                ),
                (
                    "pricing_timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="When the pricing calculation was performed."),
                ),
                (
                    "pricing_config",
                    models.JSONField(
                        blank=True, help_text="Pricing configuration used for cost calculation.", null=True
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Parent chat for easy querying of all token costs per chat.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_costs",
                        to="core.chat",
                    ),
                ),
                (
                    "chat_message",
                    models.OneToOneField(
                        help_text="One-to-one relationship with ChatMessage.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_cost",
                        to="core.chatmessage",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="One-to-one relationship with ProjectDetails.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_cost",
                        to="core.projectdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who generated this token cost.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Token Cost",
                "verbose_name_plural": "Chat Token Costs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSessionCost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "session_cost_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this session cost record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="Session identifier - must be unique.", max_length=255, unique=True),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(default=0, help_text="Total number of messages in this session."),
                ),
                (
                    "total_input_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total input tokens across all messages in session.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total output tokens across all messages in session.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total tokens across all messages in session.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0E-8"),
                        help_text="Total estimated cost for the entire session.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "architect_total_tokens",
                    models.PositiveIntegerField(default=0, help_text="Total tokens used by architect LLM in session."),
                ),
                (
                    "architect_total_cost",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0E-8"),
                        help_text="Total cost for architect LLM in session.",
                        max_digits=10,
                    ),
                ),
                (
                    "developer_total_tokens",
                    models.PositiveIntegerField(default=0, help_text="Total tokens used by developer LLM in session."),
                ),
                (
                    "developer_total_cost",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0E-8"),
                        help_text="Total cost for developer LLM in session.",
                        max_digits=10,
                    ),
                ),
                ("session_start_time", models.DateTimeField(auto_now_add=True, help_text="When the session started.")),
                (
                    "last_message_time",
                    models.DateTimeField(auto_now=True, help_text="When the last message was processed."),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether the session is still active.")),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Primary chat for this session.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_costs",
                        to="core.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this session.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session Cost",
                "verbose_name_plural": "Chat Session Costs",
                "ordering": ["-last_message_time"],
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="chat_intent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional intent associated with this chat.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chats",
                to="core.chatintent",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="project",
            field=models.ForeignKey(
                help_text="Project to which this chat belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_project",
                to="core.projectdetails",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                help_text="User who created (owns) this chat.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BackupModels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("model_data", models.JSONField(default=dict)),
                (
                    "config_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="backup_model", to="core.configmodels"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_model",
                        to="core.projectdetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("token_hash", models.CharField(blank=True, default="", max_length=64)),
                ("signature", models.CharField(blank=True, default="", max_length=128)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("is_disabled", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectOnboardingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("completed_tasks", models.JSONField(default=list)),
                ("skipped_tasks", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sessions",
                        to="core.projectdetails",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.onboardingtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_project_onboarding_session",
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("member_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(default="admin", max_length=50)),
                (
                    "is_login_onboarding_msg",
                    models.BooleanField(
                        db_comment="Flag to indicate whether the onboarding messages are shown", default=True
                    ),
                ),
                ("is_org_admin", models.BooleanField(default=True)),
                (
                    "starter_projects_created",
                    models.BooleanField(
                        db_comment="Flag to indicate whether starter projects have been created", default=False
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_members",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Member",
                "verbose_name_plural": "Organization Members",
                "db_table": "tenant_account_organizationmember",
                "unique_together": {("user", "organization")},
            },
        ),
        migrations.AddConstraint(
            model_name="csvmodels",
            constraint=models.UniqueConstraint(
                fields=("project_instance", "csv_name"), name="unique_csv_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="configmodels",
            constraint=models.UniqueConstraint(
                fields=("project_instance", "model_name"), name="unique_model_name_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="chattokencost",
            index=models.Index(fields=["chat", "created_at"], name="core_chatto_chat_id_bdcc7a_idx"),
        ),
        migrations.AddIndex(
            model_name="chattokencost",
            index=models.Index(fields=["session_id"], name="core_chatto_session_4787aa_idx"),
        ),
        migrations.AddIndex(
            model_name="chattokencost",
            index=models.Index(fields=["user", "created_at"], name="core_chatto_user_id_86e7d2_idx"),
        ),
        migrations.AddIndex(
            model_name="chattokencost",
            index=models.Index(fields=["total_estimated_cost"], name="core_chatto_total_e_88bb2d_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsessioncost",
            index=models.Index(fields=["session_id"], name="core_chatse_session_d433e0_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsessioncost",
            index=models.Index(fields=["user", "last_message_time"], name="core_chatse_user_id_2a0f6f_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsessioncost",
            index=models.Index(fields=["chat", "last_message_time"], name="core_chatse_chat_id_44df36_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsessioncost",
            index=models.Index(fields=["total_estimated_cost"], name="core_chatse_total_e_f2150f_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsessioncost",
            index=models.Index(fields=["is_active"], name="core_chatse_is_acti_c97570_idx"),
        ),
    ]
