# Generated by Django 4.2.10 on 2026-04-01 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("version_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.PositiveIntegerField()),
                ("model_data", models.JSONField(default=dict)),
                ("commit_message", models.CharField(blank=True, default="", max_length=500)),
                ("change_summary", models.TextField(blank=True, null=True)),
                ("committed_by", models.JSONField(default=dict)),
                ("user_name_snapshot", models.TextField(blank=True, default="")),
                ("user_email_snapshot", models.TextField(blank=True, default="")),
                ("user_role_snapshot", models.TextField(blank=True, default="")),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("is_published", models.BooleanField(default=False)),
                ("is_auto_commit", models.BooleanField(default=False)),
                ("rollback_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "git_sync_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "N/A"),
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="not_applicable",
                        max_length=20,
                    ),
                ),
                ("git_commit_sha", models.CharField(blank=True, default="", max_length=40)),
                ("extracted_model_name", models.CharField(blank=True, db_index=True, default="", max_length=200)),
                ("extracted_source_table", models.CharField(blank=True, db_index=True, default="", max_length=200)),
                ("extracted_transformation_count", models.PositiveIntegerField(default=0)),
                ("extracted_has_incremental_filter", models.BooleanField(default=False)),
                ("extracted_model_count", models.PositiveIntegerField(default=0)),
                (
                    "config_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.configmodels",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_versions",
                        to="core.projectdetails",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="UserDraft",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("draft_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("owner_id", models.CharField(max_length=255)),
                ("owner", models.JSONField(default=dict)),
                ("base_version_number", models.PositiveIntegerField(default=0)),
                ("draft_data", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("last_auto_save", models.DateTimeField(blank=True, null=True)),
                ("is_dirty", models.BooleanField(default=False)),
                ("lock_acquired_at", models.DateTimeField(blank=True, null=True)),
                ("lock_expires_at", models.DateTimeField(blank=True, null=True)),
                ("lock_token", models.UUIDField(default=uuid.uuid4)),
                (
                    "config_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="drafts", to="core.configmodels"
                    ),
                ),
                (
                    "draft_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_drafts",
                        to="core.modelversion",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationConflict",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "conflict_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("draft_version_number", models.PositiveIntegerField()),
                ("transformation_path", models.CharField(max_length=300)),
                ("draft_transformation", models.JSONField(default=dict)),
                ("published_transformation", models.JSONField(default=dict)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted (Mine)"),
                            ("rejected", "Rejected (Theirs)"),
                            ("merged", "Merged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_data", models.JSONField(blank=True, default=dict)),
                ("resolved_by", models.JSONField(default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conflicts", to="core.configmodels"
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conflicts", to="core.userdraft"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conflicts", to="core.modelversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitRepoConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "git_repo_config_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("repo_type", models.CharField(choices=[("default", "Default"), ("custom", "Custom")], max_length=20)),
                ("repo_url", models.CharField(max_length=500)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("pat", "PAT"), ("ssh", "SSH"), ("oauth", "OAuth")], default="pat", max_length=20
                    ),
                ),
                ("encrypted_credentials", models.JSONField(default=dict)),
                ("branch_name", models.CharField(default="main", max_length=200)),
                ("base_path", models.CharField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[("connected", "Connected"), ("error", "Error"), ("pending", "Pending")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.JSONField(default=dict)),
                ("last_modified_by", models.JSONField(default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_configs",
                        to="core.projectdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionAuditEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("version_committed", "Version Committed"),
                            ("version_rolled_back", "Version Rolled Back"),
                            ("draft_saved", "Draft Saved"),
                            ("draft_discarded", "Draft Discarded"),
                            ("conflict_resolved", "Conflict Resolved"),
                            ("conflict_finalized", "Conflict Finalized"),
                            ("version_viewed", "Version Viewed"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("version_number", models.PositiveIntegerField(blank=True, null=True)),
                ("actor", models.JSONField(default=dict)),
                ("user_name_snapshot", models.TextField(blank=True, default="")),
                ("user_email_snapshot", models.TextField(blank=True, default="")),
                ("user_role_snapshot", models.TextField(blank=True, default="")),
                ("commit_message", models.CharField(blank=True, default="", max_length=500)),
                ("changes_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "config_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.configmodels",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.projectdetails",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="core.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["config_model", "-created_at"], name="idx_audit_model_timeline"),
                    models.Index(
                        fields=["project_instance", "event_type", "-created_at"], name="idx_audit_project_events"
                    ),
                    models.Index(
                        fields=["organization", "project_instance", "-created_at"], name="idx_audit_org_isolation"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="userdraft",
            index=models.Index(fields=["owner_id", "config_model"], name="idx_draft_owner_lookup"),
        ),
        migrations.AddIndex(
            model_name="userdraft",
            index=models.Index(fields=["last_auto_save"], name="idx_draft_stale_cleanup"),
        ),
        migrations.AddConstraint(
            model_name="userdraft",
            constraint=models.UniqueConstraint(fields=("config_model", "owner_id"), name="unique_draft_per_user_model"),
        ),
        migrations.AddIndex(
            model_name="transformationconflict",
            index=models.Index(fields=["config_model", "draft"], name="idx_conflict_model_draft"),
        ),
        migrations.AddIndex(
            model_name="transformationconflict",
            index=models.Index(fields=["resolution_status"], name="idx_conflict_status"),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(fields=["project_instance", "-version_number"], name="idx_mv_proj_version"),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["project_instance", "is_published", "-created_at"], name="idx_mv_proj_published"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(fields=["organization", "project_instance", "-created_at"], name="idx_mv_org_isolation"),
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("config_model__isnull", True)),
                fields=("project_instance", "version_number"),
                name="unique_project_version",
            ),
        ),
        migrations.AddIndex(
            model_name="gitrepoconfig",
            index=models.Index(fields=["project", "is_active"], name="idx_grc_project_active"),
        ),
        migrations.AddIndex(
            model_name="gitrepoconfig",
            index=models.Index(fields=["organization", "is_deleted"], name="idx_grc_org"),
        ),
        migrations.AddConstraint(
            model_name="gitrepoconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("project",),
                name="unique_active_git_config_per_project",
            ),
        ),
    ]
