# Generated by Django 4.2.10 on 2026-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_version_history_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="is_current",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
