# Generated by Django 4.2.10 on 2026-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_is_current_to_modelversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepoconfig",
            name="pr_base_branch",
            field=models.CharField(default="main", max_length=255),
        ),
        migrations.AddField(
            model_name="gitrepoconfig",
            name="pr_branch_prefix",
            field=models.CharField(default="visitran/", max_length=100),
        ),
        migrations.AddField(
            model_name="gitrepoconfig",
            name="pr_workflow_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="pr_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="pr_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
