# Generated by Django 4.2.10 on 2026-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pr_workflow_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gitrepoconfig",
            name="pr_workflow_enabled",
        ),
        migrations.AddField(
            model_name="gitrepoconfig",
            name="pr_mode",
            field=models.CharField(
                choices=[("disabled", "Disabled"), ("auto", "Auto"), ("manual", "Manual")],
                default="disabled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="git_branch_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
