# Generated by Django 4.2.10 on 2026-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pr_mode_and_branch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelversion",
            name="model_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
