sonar.projectKey=zipstack_visitran_python
sonar.organization=zipstack
sonar.python.version=3.10
sonar.python.coverage.reportPaths=./coverage.xml
sonar.exclusions=visitran_ui/**
sonar.scm.provider=git
sonar.verbose=false
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/duckdbuitest/**, **/tests/**, tasks.py, ci/*, **/starter_project/**
