"""Django settings for server project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from typing import Optional

from dotenv import find_dotenv, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)
DJANGO_ENV = os.getenv("DJANGO_ENV", "development")
IS_CLOUD = os.getenv("IS_CLOUD", "false").strip().lower() == "true"
PATH_PREFIX = os.environ.get("PATH_PREFIX", "/api/v1").strip("/")
CACHE_TTL_SEC = os.environ.get("CACHE_TTL_SEC", 10800)
LOGGING_SERVICE_ACCOUNT_INFO = os.environ.get("LOGGING_SERVICE_ACCOUNT_INFO", "")

ENV_FILE = find_dotenv()
if ENV_FILE:
    load_dotenv(ENV_FILE)

missing_settings = []


def get_required_setting(setting_key: str, default: Optional[str] = None) -> Optional[str]:
    """Get the value of an environment variable specified by the given key. Add
    missing keys to `missing_settings` so that exception can be raised at the
    end.

    Args:
        key (str): The key of the environment variable
        default (Optional[str], optional): Default value to return in case of
                                           env not found. Defaults to None.

    Returns:
        Optional[str]: The value of the environment variable if found,
                       otherwise the default value.
                       :param default:
                       :param setting_key:
    """
    data = os.environ.get(setting_key, default)
    if not data:
        missing_settings.append(setting_key)
    return data


WEB_APP_ORIGIN_URL = os.environ.get("WEB_APP_ORIGIN_URL", "http://localhost:3000")
LOGIN_NEXT_URL = os.environ.get("LOGIN_NEXT_URL", "http://localhost:3000/project/list")
LANDING_URL = os.environ.get("LANDING_URL", "http://localhost:3000")
ERROR_URL = os.environ.get("ERROR_URL", "http://localhost:3000/error")

REDIS_USER = os.environ.get("REDIS_USER", "default")
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", "")
REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")
REDIS_DB = os.environ.get("REDIS_DB", "")

REDIS_URL_STREAMER = os.getenv("REDIS_URL_STREAMER") or f"redis://{REDIS_HOST}:{REDIS_PORT}/10"

SOCKET_HOST = os.environ.get("SOCKET_HOST", "localhost")
SOCKET_PORT = int(os.environ.get("SOCKET_PORT", 4000))

SHARED_APPS = [
    # Django apps
    "django_celery_beat",
    "django.contrib.auth",
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "corsheaders",
    # Core apps
    "backend.core",
    # Scheduler (uses label "job_scheduler" for DB compatibility)
    "backend.core.scheduler.apps.SchedulerConfig",
]

ROOT_URLCONF = "backend.server.base_urls"

SETTINGS_PATH = os.path.normpath(os.path.dirname(__file__))
TEMPLATE_DIRS = (os.path.join(SETTINGS_PATH, "templates"),)

WSGI_APPLICATION = "backend.server.wsgi.application"

SILENCED_SYSTEM_CHECKS = ["urls.W002"]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"
USE_TZ = True

USE_I18N = True

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "core.User"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ALLOWED_HOSTS = ["*"]

SOCKET_IO_MANAGER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"

CSRF_TRUSTED_ORIGINS = [LANDING_URL]
CORS_ALLOWED_ORIGINS = [
    LANDING_URL,  # Add your frontend URL here
]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

ENABLE_LOG_HISTORY = get_required_setting("ENABLE_LOG_HISTORY", "False")
LOG_HISTORY_CONSUMER_INTERVAL = int(get_required_setting("LOG_HISTORY_CONSUMER_INTERVAL", "60"))
LOGS_BATCH_LIMIT = int(get_required_setting("LOGS_BATCH_LIMIT", "30"))
CELERY_BROKER_URL = get_required_setting("CELERY_BROKER_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_IMPORTS = ["backend.core.scheduler.celery_tasks"]
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_MAX_RETRIES = 3
CELERY_TASK_RETRY_BACKOFF = 60  # Time in seconds before retrying the task
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

SAMPLE_CONNECTION = {
    "host": os.environ.get("DB_SAMPLE_HOST"),
    "port": os.environ.get("DB_SAMPLE_PORT"),
    "user": os.environ.get("DB_SAMPLE_USER"),
    "passw": os.environ.get("DB_SAMPLE_PASSWORD"),
    "dbname": os.environ.get("DB_SAMPLE_DBNAME"),
    "schema": os.environ.get("DB_SAMPLE_SCHEMA"),
}

SAMPLE_CONNECTION_PASSWORD = os.environ.get("SAMPLE_CONNECTION_PASSWORD", "")
SAMPLE_PROJECT_LIMIT = os.environ.get("SAMPLE_PROJECT_LIMIT", 10)

INTERNAL_SERVICE_API_KEY = os.environ.get("INTERNAL_SERVICE_API_KEY")

AI_SERVER_BASE_URL = os.environ.get("AI_SERVER_BASE_URL", "http://localhost:8001")

# API Key Auth — shared secrets for AI server communication
SERVER_SIGNING_SECRET = os.environ.get("SERVER_SIGNING_SECRET", "")
X_INTERNAL_SECRET = os.environ.get("X_INTERNAL_SECRET", "")

# Visitran cloud platform URL (used in OSS error messages for key management)
VISITRAN_PLATFORM_URL = os.environ.get("VISITRAN_PLATFORM_URL", "https://app.visitran.com")

# OSS: API key for connecting to Visitran AI cloud service via WebSocket
# Get your key from VISITRAN_PLATFORM_URL → Settings → API Keys
VISITRAN_AI_KEY = os.environ.get("VISITRAN_AI_KEY", "")

# API key limits (overridable via .env)
MAX_KEYS_PER_USER = int(os.environ.get("MAX_KEYS_PER_USER", "5"))
API_KEY_EXPIRY_DAYS = int(os.environ.get("API_KEY_EXPIRY_DAYS", "90"))

LLM_EVENT_STREAMER_NAME = os.environ.get("LLM_EVENT_STREAMER_NAME") or "LLM_PROMPT_REQUEST"

# This could be either RedisManager or eventlet
WEBSOCKET_MANAGER = os.environ.get("SOCKET_MANAGER", "RedisManager")

REDIS_STREAMER_CONSUMER = os.getenv("HOSTNAME", "default-consumer")
REDIS_STREAMER_GROUP_NAME = "VISITRAN_BACKEND"

GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME", "visitran-uploads")


SESSION_COOKIE_AGE = 604800  # 1 week (same as of scalekit)
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", True)  # HTTPS only
SESSION_COOKIE_HTTPONLY = os.environ.get("SESSION_COOKIE_HTTPONLY", True)  # Prevent JS access
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF protection
SESSION_SAVE_EVERY_REQUEST = False  # True, if Extend session on activity
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", True)

VISITRAN_ENCRYPTION_KEY = os.environ.get("VISITRAN_ENCRYPTION_KEY")

# Execution mode: controls whether to use legacy Python path or direct SQL path
# Values: "legacy" (default), "direct"
# - legacy: YAML → Python codegen → Ibis → SQL (current behavior)
# - direct: YAML → SQL Builder → SQL (no Python layer)
VISITRAN_EXECUTION_MODE = os.environ.get("VISITRAN_EXECUTION_MODE", "legacy")

# RSA Encryption Keys for Network Communication
# Note: The actual key resolution (with .env fallback) happens in rsa_encryption.py
# These settings are the primary source, but rsa_encryption._resolve_pem() will
# fall back to os.environ and .env file if these are empty.
VISITRAN_RSA_PRIVATE_KEY = os.environ.get("VISITRAN_RSA_PRIVATE_KEY") or None
VISITRAN_RSA_PUBLIC_KEY = os.environ.get("VISITRAN_RSA_PUBLIC_KEY") or None
