import uuid
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models

from backend.core.models.chat import Chat
from backend.core.models.chat_message import ChatMessage
from backend.core.models.project_details import ProjectDetails
from backend.core.models.user_model import User
from utils.models.base_model import BaseModel


class ChatTokenCost(BaseModel):
    """Tracks token usage and cost information for each chat message.

    Stores detailed breakdown of tokens used by architect and developer
    LLMs.
    """

    token_cost_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, help_text="Unique identifier for this token cost record."
    )

    project = models.ForeignKey(
        ProjectDetails,
        on_delete=models.CASCADE,
        related_name="token_cost",
        help_text="One-to-one relationship with ProjectDetails.",
    )

    # Relationships
    chat_message = models.OneToOneField(
        ChatMessage,
        on_delete=models.CASCADE,
        related_name="token_cost",
        help_text="One-to-one relationship with ChatMessage.",
    )

    chat = models.ForeignKey(
        Chat,
        on_delete=models.CASCADE,
        related_name="token_costs",
        help_text="Parent chat for easy querying of all token costs per chat.",
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name="token_costs",
        help_text="User who generated this token cost.",
    )

    # Session tracking
    session_id = models.CharField(
        max_length=255,
        help_text="Session identifier for grouping related requests (Channel Id often generated by org_id, "
        "project_id, chat_id and chat_message_id",
    )

    chat_intent = models.CharField(max_length=255, help_text="Intent type of the chat model")

    # Architect LLM Usage
    architect_model_name = models.CharField(max_length=255, help_text="Name of the architect LLM model used.")

    architect_input_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Number of input tokens used by architect LLM."
    )

    architect_output_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Number of output tokens generated by architect LLM."
    )

    architect_total_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Total tokens (input + output) used by architect LLM."
    )

    architect_estimated_cost = models.DecimalField(
        max_digits=10,
        decimal_places=8,
        default=Decimal("0.00000000"),
        validators=[MinValueValidator(Decimal("0"))],
        help_text="Estimated cost in USD for architect LLM usage.",
    )

    # Developer LLM Usage
    developer_model_name = models.CharField(max_length=255, help_text="Name of the developer LLM model used.")

    developer_input_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Number of input tokens used by developer LLM."
    )

    developer_output_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Number of output tokens generated by developer LLM."
    )

    developer_total_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Total tokens (input + output) used by developer LLM."
    )

    developer_estimated_cost = models.DecimalField(
        max_digits=10,
        decimal_places=8,
        default=Decimal("0.00000000"),
        validators=[MinValueValidator(Decimal("0"))],
        help_text="Estimated cost in USD for developer LLM usage.",
    )

    # Combined totals
    total_input_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Combined input tokens from both LLMs."
    )

    total_output_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Combined output tokens from both LLMs."
    )

    total_tokens = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)], help_text="Combined total tokens from both LLMs."
    )

    total_estimated_cost = models.DecimalField(
        max_digits=10,
        decimal_places=8,
        default=Decimal("0.00000000"),
        validators=[MinValueValidator(Decimal("0"))],
        help_text="Total estimated cost in USD for both LLMs.",
    )

    # Processing time
    processing_time_ms = models.PositiveIntegerField(
        default=0, help_text="Time taken in milliseconds for token processing."
    )

    # Additional metadata
    pricing_timestamp = models.DateTimeField(auto_now_add=True, help_text="When the pricing calculation was performed.")

    pricing_config = models.JSONField(
        null=True, blank=True, help_text="Pricing configuration used for cost calculation."
    )

    def save(self, *args, **kwargs):
        """Calculate totals before saving."""
        self.total_input_tokens = self.architect_input_tokens + self.developer_input_tokens
        self.total_output_tokens = self.architect_output_tokens + self.developer_output_tokens
        self.total_tokens = self.architect_total_tokens + self.developer_total_tokens
        self.total_estimated_cost = self.architect_estimated_cost + self.developer_estimated_cost
        super().save(*args, **kwargs)

    @property
    def cost_per_token(self):
        """Calculate average cost per token."""
        if self.total_tokens > 0:
            return self.total_estimated_cost / self.total_tokens
        return Decimal("0.00000000")

    @property
    def architect_cost_breakdown(self):
        """Return architect cost breakdown as dict."""
        return {
            "model_name": self.architect_model_name,
            "input_tokens": self.architect_input_tokens,
            "output_tokens": self.architect_output_tokens,
            "total_tokens": self.architect_total_tokens,
            "estimated_cost": float(self.architect_estimated_cost),
        }

    @property
    def developer_cost_breakdown(self):
        """Return developer cost breakdown as dict."""
        return {
            "model_name": self.developer_model_name,
            "input_tokens": self.developer_input_tokens,
            "output_tokens": self.developer_output_tokens,
            "total_tokens": self.developer_total_tokens,
            "estimated_cost": float(self.developer_estimated_cost),
        }

    def __str__(self):
        return f"TokenCost for Message {self.chat_message.chat_message_id} - ${self.total_estimated_cost}"

    class Meta:
        verbose_name = "Chat Token Cost"
        verbose_name_plural = "Chat Token Costs"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["chat", "created_at"]),
            models.Index(fields=["session_id"]),
            models.Index(fields=["user", "created_at"]),
            models.Index(fields=["total_estimated_cost"]),
        ]
