"""
Django models for SQL Validation Storage.

This module provides database persistence for SQL validation results,
enabling post-execution analysis and reporting.
"""

import uuid
from django.db import models
from django.utils import timezone

from utils.models.base_model import BaseModel


class SQLValidationResult(BaseModel):
    """
    Stores SQL comparison results between legacy and direct execution paths.

    Each record represents a single validation of SQL output from both
    execution paths for a specific model.
    """

    validation_id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for this validation result."
    )

    # Model identification
    model_name = models.CharField(
        max_length=255,
        db_index=True,
        help_text="Name of the model being validated (schema.model format)."
    )

    schema_name = models.CharField(
        max_length=128,
        blank=True,
        default="",
        help_text="Schema name for the model."
    )

    # SQL content
    legacy_sql = models.TextField(
        help_text="SQL generated by the legacy Python code path."
    )

    direct_sql = models.TextField(
        help_text="SQL generated by the direct Ibis execution path."
    )

    # Validation result
    match_status = models.BooleanField(
        default=False,
        db_index=True,
        help_text="Whether the SQL outputs match (True = match, False = mismatch)."
    )

    match_type = models.CharField(
        max_length=32,
        default="no_match",
        help_text="Type of match: exact, normalized, no_match."
    )

    diff_output = models.TextField(
        blank=True,
        default="",
        help_text="Detailed diff showing differences between SQL outputs."
    )

    # Execution context
    execution_id = models.CharField(
        max_length=64,
        blank=True,
        db_index=True,
        help_text="Execution ID linking to DAG execution run."
    )

    execution_mode = models.CharField(
        max_length=32,
        default="parallel",
        help_text="Execution mode: legacy, direct, parallel."
    )

    execution_context = models.JSONField(
        default=dict,
        blank=True,
        help_text="Additional execution context metadata."
    )

    # Timing
    validated_at = models.DateTimeField(
        default=timezone.now,
        db_index=True,
        help_text="Timestamp when validation was performed."
    )

    legacy_execution_ms = models.FloatField(
        null=True,
        blank=True,
        help_text="Legacy path execution time in milliseconds."
    )

    direct_execution_ms = models.FloatField(
        null=True,
        blank=True,
        help_text="Direct path execution time in milliseconds."
    )

    class Meta:
        db_table = "sql_validation_results"
        ordering = ["-validated_at"]
        indexes = [
            models.Index(fields=["model_name", "validated_at"]),
            models.Index(fields=["match_status", "validated_at"]),
            models.Index(fields=["execution_id"]),
        ]

    def __str__(self) -> str:
        status = "✓" if self.match_status else "✗"
        return f"{status} {self.model_name} @ {self.validated_at}"


class ValidationSummary(BaseModel):
    """
    Aggregated validation statistics for a DAG execution run.

    Provides summary metrics for post-execution analysis and reporting.
    """

    summary_id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for this summary."
    )

    execution_id = models.CharField(
        max_length=64,
        unique=True,
        db_index=True,
        help_text="Execution ID for the DAG run."
    )

    # Counts
    total_models = models.IntegerField(
        default=0,
        help_text="Total number of models validated."
    )

    matched_count = models.IntegerField(
        default=0,
        help_text="Number of models with matching SQL."
    )

    mismatched_count = models.IntegerField(
        default=0,
        help_text="Number of models with mismatched SQL."
    )

    skipped_count = models.IntegerField(
        default=0,
        help_text="Number of models skipped (no legacy SQL available)."
    )

    # Rates
    match_rate = models.FloatField(
        default=0.0,
        help_text="Percentage of models with matching SQL (0.0 to 1.0)."
    )

    # Timing
    total_legacy_ms = models.FloatField(
        default=0.0,
        help_text="Total legacy execution time in milliseconds."
    )

    total_direct_ms = models.FloatField(
        default=0.0,
        help_text="Total direct execution time in milliseconds."
    )

    speedup_factor = models.FloatField(
        default=1.0,
        help_text="Speedup factor (legacy_time / direct_time)."
    )

    # Execution context
    execution_mode = models.CharField(
        max_length=32,
        default="parallel",
        help_text="Execution mode used."
    )

    started_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When execution started."
    )

    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When execution completed."
    )

    # Mismatched models list
    mismatched_models = models.JSONField(
        default=list,
        blank=True,
        help_text="List of model names that had mismatches."
    )

    class Meta:
        db_table = "validation_summaries"
        ordering = ["-completed_at"]

    def __str__(self) -> str:
        return f"Summary {self.execution_id}: {self.match_rate:.1%} match rate"


class ModelAllowlist(BaseModel):
    """
    Configuration for models allowed to use direct execution.

    Models not on the allowlist bypass direct execution and use legacy path only.
    """

    allowlist_id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for this allowlist entry."
    )

    model_name = models.CharField(
        max_length=255,
        unique=True,
        db_index=True,
        help_text="Model name pattern (supports wildcards with *)."
    )

    is_enabled = models.BooleanField(
        default=True,
        help_text="Whether this model is enabled for direct execution."
    )

    priority = models.IntegerField(
        default=0,
        help_text="Priority for matching (higher = matched first)."
    )

    notes = models.TextField(
        blank=True,
        default="",
        help_text="Notes about why this model is allowlisted."
    )

    added_by = models.CharField(
        max_length=128,
        blank=True,
        default="",
        help_text="Who added this allowlist entry."
    )

    class Meta:
        db_table = "model_allowlist"
        ordering = ["-priority", "model_name"]

    def __str__(self) -> str:
        status = "enabled" if self.is_enabled else "disabled"
        return f"{self.model_name} ({status})"


class FallbackEvent(BaseModel):
    """
    Records when direct execution fails and falls back to legacy path.

    Used for monitoring and debugging fallback frequency.
    """

    event_id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for this fallback event."
    )

    model_name = models.CharField(
        max_length=255,
        db_index=True,
        help_text="Model that triggered the fallback."
    )

    execution_id = models.CharField(
        max_length=64,
        blank=True,
        db_index=True,
        help_text="Execution ID when fallback occurred."
    )

    failure_reason = models.TextField(
        help_text="Description of why direct execution failed."
    )

    error_type = models.CharField(
        max_length=128,
        blank=True,
        default="",
        help_text="Type/class of the error that occurred."
    )

    error_traceback = models.TextField(
        blank=True,
        default="",
        help_text="Full traceback of the error."
    )

    fallback_succeeded = models.BooleanField(
        default=True,
        help_text="Whether the legacy fallback succeeded."
    )

    occurred_at = models.DateTimeField(
        default=timezone.now,
        db_index=True,
        help_text="When the fallback occurred."
    )

    direct_execution_ms = models.FloatField(
        null=True,
        blank=True,
        help_text="Time spent on direct execution before failure."
    )

    fallback_execution_ms = models.FloatField(
        null=True,
        blank=True,
        help_text="Time spent on legacy fallback execution."
    )

    class Meta:
        db_table = "fallback_events"
        ordering = ["-occurred_at"]
        indexes = [
            models.Index(fields=["model_name", "occurred_at"]),
            models.Index(fields=["error_type", "occurred_at"]),
        ]

    def __str__(self) -> str:
        status = "✓" if self.fallback_succeeded else "✗"
        return f"{status} Fallback: {self.model_name} @ {self.occurred_at}"
