# Generated by Django 4.2.10 on 2026-03-16 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_seed_data"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTaskDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(max_length=255)),
                ("task_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SUCCESS", "Success"),
                            ("FAILED PERMANENTLY", "Failed Permanently"),
                            ("Retrying", "Retrying"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_run_time", models.DateTimeField(blank=True, null=True)),
                ("task_completion_time", models.DateTimeField(blank=True, null=True)),
                ("next_run_time", models.DateTimeField(blank=True, null=True)),
                (
                    "prev_run_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SUCCESS", "Success"),
                            ("FAILED PERMANENTLY", "Failed Permanently"),
                            ("Retrying", "Retrying"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "model_configs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-model deployment configuration including materialization and incremental settings",
                    ),
                ),
                (
                    "run_timeout_seconds",
                    models.PositiveIntegerField(default=0, help_text="Max run duration in seconds. 0 = no limit."),
                ),
                ("max_retries", models.PositiveSmallIntegerField(default=0)),
                ("notify_on_failure", models.BooleanField(default=False)),
                ("notify_on_success", models.BooleanField(default=False)),
                ("notification_emails", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "environment",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.environmentmodels"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "periodic_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_tasks", to="core.projectdetails"
                    ),
                ),
                (
                    "trigger_on_complete",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job to trigger when this job completes successfully.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_by",
                        to="job_scheduler.usertaskdetails",
                    ),
                ),
            ],
            options={
                "db_table": "job_scheduler_usertaskdetails",
            },
        ),
        migrations.CreateModel(
            name="WatermarkHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("watermark_value", models.TextField(help_text="Watermark value at time of execution")),
                ("execution_time", models.DateTimeField(help_text="When this watermark was recorded")),
                (
                    "records_processed",
                    models.IntegerField(default=0, help_text="Number of records processed in this run"),
                ),
                (
                    "execution_duration_seconds",
                    models.FloatField(blank=True, help_text="Time taken for this incremental run", null=True),
                ),
                (
                    "strategy_used",
                    models.CharField(help_text="Watermark strategy used for this execution", max_length=20),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional execution metadata")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "user_task",
                    models.ForeignKey(
                        help_text="Reference to the job that executed this watermark",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watermark_history",
                        to="job_scheduler.usertaskdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watermark History",
                "verbose_name_plural": "Watermark Histories",
                "db_table": "job_scheduler_watermarkhistory",
                "ordering": ["-execution_time"],
                "indexes": [
                    models.Index(fields=["user_task", "execution_time"], name="wm_hist_task_time_idx"),
                    models.Index(fields=["organization_id", "execution_time"], name="wm_hist_org_time_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskRunHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(help_text="Celery task ID for this specific run.", max_length=255)),
                ("retry_num", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                            ("RETRY", "Retry"),
                        ],
                        default="PENDING",
                        help_text="Current status of the task run.",
                        max_length=50,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("kwargs", models.JSONField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "user_task_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_runs",
                        to="job_scheduler.usertaskdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Run History",
                "verbose_name_plural": "Task Run Histories",
                "db_table": "job_scheduler_taskrunhistory",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(fields=["task_id"], name="job_schedul_task_id_4dc8ac_idx"),
                    models.Index(fields=["status"], name="job_schedul_status_86a75c_idx"),
                    models.Index(fields=["user_task_detail"], name="job_schedul_user_ta_5cd43a_idx"),
                ],
                "unique_together": {("task_id", "retry_num")},
            },
        ),
    ]
