
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: types.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EventInfo(betterproto.Message):
    """Common event info."""

    name: str = betterproto.string_field(1)
    code: str = betterproto.string_field(2)
    msg: str = betterproto.string_field(3)
    level: str = betterproto.string_field(4)
    invocation_id: str = betterproto.string_field(5)
    pid: int = betterproto.int32_field(6)
    thread: str = betterproto.string_field(7)
    ts: str = betterproto.string_field(8)
    extra: dict[str, str] = betterproto.map_field(9, betterproto.TYPE_STRING, betterproto.TYPE_STRING)
    category: str = betterproto.string_field(10)


@dataclass
class MainReportVersion(betterproto.Message):
    version: str = betterproto.string_field(1)


@dataclass
class MainReportVersionMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "MainReportVersion" = betterproto.message_field(2)


@dataclass
class StarterProjectPath(betterproto.Message):
    dir: str = betterproto.string_field(1)


@dataclass
class StarterProjectPathMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "StarterProjectPath" = betterproto.message_field(2)


@dataclass
class ConfigFolderDirectory(betterproto.Message):
    """A018."""

    dir: str = betterproto.string_field(1)


@dataclass
class ConfigFolderDirectoryMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ConfigFolderDirectory" = betterproto.message_field(2)


@dataclass
class SettingUpProfile(betterproto.Message):
    """A023."""

    pass


@dataclass
class SettingUpProfileMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SettingUpProfile" = betterproto.message_field(2)


@dataclass
class InvalidProfileTemplateYAML(betterproto.Message):
    """A024."""

    pass


@dataclass
class InvalidProfileTemplateYAMLMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "InvalidProfileTemplateYAML" = betterproto.message_field(2)


@dataclass
class ProjectFileAlreadyExists(betterproto.Message):
    """A025."""

    name: str = betterproto.string_field(1)


@dataclass
class ProjectFileAlreadyExistsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ProjectFileAlreadyExists" = betterproto.message_field(2)


@dataclass
class ProjectCreated(betterproto.Message):
    """A026."""

    project_name: str = betterproto.string_field(1)


@dataclass
class ProjectCreatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ProjectCreated" = betterproto.message_field(2)


@dataclass
class SeedEventIntiated(betterproto.Message):
    """A027."""

    seed_path: str = betterproto.string_field(1)


@dataclass
class SeedEventIntiatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SeedEventIntiated" = betterproto.message_field(2)


@dataclass
class SeedFilesFound(betterproto.Message):
    """A028."""

    sf_path: str = betterproto.string_field(1)
    schema_name: str = betterproto.string_field(2)
    database_type: str = betterproto.string_field(3)


@dataclass
class SeedFilesFoundMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SeedEventIntiated" = betterproto.message_field(2)


@dataclass
class SnapshotEventIntiated(betterproto.Message):
    """A029."""

    snp_path: str = betterproto.string_field(1)


@dataclass
class SnapshotEventIntiatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SnapshotEventIntiated" = betterproto.message_field(2)


@dataclass
class SnapshotFilesFound(betterproto.Message):
    """A030."""

    snp_path: str = betterproto.string_field(1)


@dataclass
class SnapshotFilesFoundMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SnapshotFilesFound" = betterproto.message_field(2)


@dataclass
class IncludesExcludesList(betterproto.Message):
    """A031."""

    includes: str = betterproto.string_field(1)
    excludes: str = betterproto.string_field(2)


@dataclass
class IncludesExcludesListMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "IncludesExcludesList" = betterproto.message_field(2)


@dataclass
class AdapterEventDebug(betterproto.Message):
    """E001."""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: list[str] = betterproto.string_field(3)


@dataclass
class AdapterEventDebugMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "AdapterEventDebug" = betterproto.message_field(2)


@dataclass
class AdapterEventInfo(betterproto.Message):
    """E002."""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: list[str] = betterproto.string_field(3)


@dataclass
class AdapterEventInfoMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "AdapterEventInfo" = betterproto.message_field(2)


@dataclass
class AdapterEventWarning(betterproto.Message):
    """E003."""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: list[str] = betterproto.string_field(3)


@dataclass
class AdapterEventWarningMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "AdapterEventWarning" = betterproto.message_field(2)


@dataclass
class AdapterEventError(betterproto.Message):
    """E004."""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: list[str] = betterproto.string_field(3)
    exc_info: str = betterproto.string_field(4)


@dataclass
class AdapterEventErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "AdapterEventError" = betterproto.message_field(2)


@dataclass
class AdapterType(betterproto.Message):
    database_name: str = betterproto.string_field(1)


@dataclass
class AdapterTypeMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "AdapterType" = betterproto.message_field(2)


@dataclass
class SqlExecutionCompleted(betterproto.Message):
    """I - Project Parsing"""

    pass


@dataclass
class SqlExecutionCompletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SqlExecutionCompleted" = betterproto.message_field(2)


@dataclass
class IntiatingRunExecution(betterproto.Message):
    model_path: str = betterproto.string_field(1)


@dataclass
class IntiatingRunExecutionMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "IntiatingRunExecution" = betterproto.message_field(2)


@dataclass
class FoundModels(betterproto.Message):
    mf: str = betterproto.string_field(1)


@dataclass
class FoundModelsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FoundModels" = betterproto.message_field(2)


@dataclass
class ImportModelsFailed(betterproto.Message):
    file_name: str = betterproto.string_field(1)
    err: str = betterproto.string_field(2)


@dataclass
class ImportModelsFailedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ImportModelsFailed" = betterproto.message_field(2)


@dataclass
class ProcessingModel(betterproto.Message):
    cls: str = betterproto.string_field(1)


@dataclass
class ProcessingModelMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ProcessingModel" = betterproto.message_field(2)


@dataclass
class ProcessingDAG(betterproto.Message):
    dest_table: str = betterproto.string_field(1)


@dataclass
class ProcessingDAGMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ProcessingDAG" = betterproto.message_field(2)


@dataclass
class ObjectForClassNotFound(betterproto.Message):
    base: str = betterproto.string_field(1)
    values: str = betterproto.string_field(2)


@dataclass
class ObjectForClassNotFoundMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ObjectForClassNotFound" = betterproto.message_field(2)


@dataclass
class FoundBaseClass(betterproto.Message):
    bases: str = betterproto.string_field(1)


@dataclass
class FoundBaseClassMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FoundBaseClass" = betterproto.message_field(2)


@dataclass
class ExecutingModelNode(betterproto.Message):
    database: str = betterproto.string_field(1)
    database_type: str = betterproto.string_field(2)
    destination_schema_name: str = betterproto.string_field(3)
    destination_table_exists: bool = betterproto.bool_field(4)
    destination_table_name: str = betterproto.string_field(5)
    destination_table_obj: str = betterproto.string_field(6)
    materialization: str = betterproto.string_field(7)
    select_statement: str = betterproto.string_field(8)
    source_schema_name: str = betterproto.string_field(9)
    source_table_name: str = betterproto.string_field(10)
    source_table_obj: str = betterproto.string_field(11)


@dataclass
class ExecutingModelNodeMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecutingModelNode" = betterproto.message_field(2)


@dataclass
class ExecutingSnapshotNode(betterproto.Message):
    database: str = betterproto.string_field(1)
    database_type: str = betterproto.string_field(2)
    source_table_name: str = betterproto.string_field(3)
    source_schema_name: str = betterproto.string_field(4)
    snapshot_table_name: str = betterproto.string_field(5)
    snapshot_schema_name: str = betterproto.string_field(6)
    unique_key: str = betterproto.string_field(7)
    strategy: str = betterproto.string_field(8)
    updated_at: str = betterproto.string_field(9)
    check_cols: list[str] = betterproto.string_field(10)
    invalidate_hard_deletes: bool = betterproto.bool_field(11)


@dataclass
class ExecutingSnapshotNodeMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecutingSnapshotNode" = betterproto.message_field(2)


@dataclass
class NodeExecutionError(betterproto.Message):
    dest_table: str = betterproto.string_field(1)
    err: str = betterproto.string_field(2)


@dataclass
class NodeExecutionErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "NodeExecutionError" = betterproto.message_field(2)


@dataclass
class IncludeExcludeError(betterproto.Message):
    includes: str = betterproto.string_field(1)
    excludes: str = betterproto.string_field(2)
    err: str = betterproto.string_field(3)


@dataclass
class IncludeExcludeErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "IncludeExcludeError" = betterproto.message_field(2)


@dataclass
class Formatting(betterproto.Message):
    """Z017."""

    msg: str = betterproto.string_field(1)


@dataclass
class FormattingMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "Formatting" = betterproto.message_field(2)


@dataclass
class SeedExecutionCompleted(betterproto.Message):
    """Z002."""

    pass


@dataclass
class SeedExecutionCompletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SeedExecutionCompleted" = betterproto.message_field(2)


@dataclass
class SnapshotExecutionCompleted(betterproto.Message):
    """Z008."""

    pass


@dataclass
class SnapshotExecutionCompletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SnapshotExecutionCompleted" = betterproto.message_field(2)


@dataclass
class SortedDAGNodes(betterproto.Message):
    sorted_dag_nodes: str = betterproto.string_field(1)


@dataclass
class SortedDAGNodesMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SortedDAGNodes" = betterproto.message_field(2)


@dataclass
class FoundModelSubClass(betterproto.Message):
    cls_str: str = betterproto.string_field(1)


@dataclass
class FoundModelSubClassMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FoundModelSubClass" = betterproto.message_field(2)


@dataclass
class FoundModelClass(betterproto.Message):
    cls_str: str = betterproto.string_field(1)


@dataclass
class FoundModelClassMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FoundModelClass" = betterproto.message_field(2)


@dataclass
class ExecutingTests(betterproto.Message):
    test_name: str = betterproto.string_field(1)
    test_path: str = betterproto.string_field(2)
    database: str = betterproto.string_field(3)
    database_type: str = betterproto.string_field(4)
    connection_string: str = betterproto.string_field(5)
    destination_schema_name: str = betterproto.string_field(6)
    destination_table_name: str = betterproto.string_field(7)
    materialization: str = betterproto.string_field(8)
    source_schema_name: str = betterproto.string_field(9)
    source_table_name: str = betterproto.string_field(10)


@dataclass
class ExecutingTestsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecutingTests" = betterproto.message_field(2)


@dataclass
class FoundTestModels(betterproto.Message):
    test_path: str = betterproto.string_field(1)


@dataclass
class FoundTestModelsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FoundTestModels" = betterproto.message_field(2)


@dataclass
class TestExecutionCompleted(betterproto.Message):
    pass


@dataclass
class TestExecutionCompletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "TestExecutionCompleted" = betterproto.message_field(2)


@dataclass
class TestExecutionFailed(betterproto.Message):
    err: str = betterproto.string_field(1)
    test_path: str = betterproto.string_field(2)
    class_name: str = betterproto.string_field(3)
    test_func: str = betterproto.string_field(4)


@dataclass
class TestExecutionFailedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "TestExecutionFailed" = betterproto.message_field(2)


@dataclass
class MaterializationType(betterproto.Message):
    materialization: str = betterproto.string_field(1)


@dataclass
class MaterializationTypeMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "MaterializationType" = betterproto.message_field(2)


@dataclass
class ModelAlreadyProcessed(betterproto.Message):
    cls: str = betterproto.string_field(1)


@dataclass
class ModelAlreadyProcessedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ModelAlreadyProcessed" = betterproto.message_field(2)


@dataclass
class UsingCachedObject(betterproto.Message):
    """bigquery."""

    objname: str = betterproto.string_field(1)
    is_cached: bool = betterproto.bool_field(2)


@dataclass
class UsingCachedObjectMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "UsingCachedObject" = betterproto.message_field(2)


@dataclass
class ReadConnectionDetails(betterproto.Message):
    dbname: str = betterproto.string_field(1)
    details: dict[str, str] = betterproto.map_field(2, betterproto.TYPE_STRING, betterproto.TYPE_STRING)


@dataclass
class ReadConnectionDetailsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ReadConnectionDetails" = betterproto.message_field(2)


@dataclass
class ExecutingQuery(betterproto.Message):
    query: str = betterproto.string_field(1)


@dataclass
class ExecutingQueryMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecutingQuery" = betterproto.message_field(2)


@dataclass
class SetExpiration(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)
    expiration: int = betterproto.int64_field(3)


@dataclass
class SetExpirationMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SetExpiration" = betterproto.message_field(2)


@dataclass
class GetTableObject(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class GetTableObjectMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "GetTableObject" = betterproto.message_field(2)


@dataclass
class GetTableColumns(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)
    columns: list[str] = betterproto.string_field(3)


@dataclass
class GetTableColumnsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "GetTableColumns" = betterproto.message_field(2)


@dataclass
class TableExists(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)
    exists: bool = betterproto.bool_field(3)


@dataclass
class TableExistsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "TableExists" = betterproto.message_field(2)


@dataclass
class ListAllTables(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    tables: list[str] = betterproto.string_field(2)


@dataclass
class ListAllTablesMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ListAllTables" = betterproto.message_field(2)


@dataclass
class GetRowCount(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)
    row_count: int = betterproto.int64_field(3)


@dataclass
class GetRowCountMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "GetRowCount" = betterproto.message_field(2)


@dataclass
class GetTableRecords(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class GetTableRecordsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "GetTableRecords" = betterproto.message_field(2)


@dataclass
class InsertInToTable(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class InsertInToTableMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "InsertInToTable" = betterproto.message_field(2)


@dataclass
class MergeInToTable(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)
    temp_table_name: str = betterproto.string_field(3)


@dataclass
class MergeInToTableMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "MergeInToTable" = betterproto.message_field(2)


@dataclass
class ExecuteEphemeral(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class ExecuteEphemeralMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecuteEphemeral" = betterproto.message_field(2)


@dataclass
class ExecuteTable(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class ExecuteTableMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecuteTable" = betterproto.message_field(2)


@dataclass
class ExecuteView(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class ExecuteViewMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecuteView" = betterproto.message_field(2)


@dataclass
class ExecuteIncrementalCreate(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class ExecuteIncrementalCreateMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecuteIncrementalCreate" = betterproto.message_field(2)


@dataclass
class ExecuteIncrementalUpdate(betterproto.Message):
    schema_name: str = betterproto.string_field(1)
    table_name: str = betterproto.string_field(2)


@dataclass
class ExecuteIncrementalUpdateMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ExecuteIncrementalUpdate" = betterproto.message_field(2)


@dataclass
class DoesNotExistError(betterproto.Message):
    object_name: str = betterproto.string_field(1)


@dataclass
class DoesNotExistErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "DoesNotExistError" = betterproto.message_field(2)


@dataclass
class NotSupportedError(betterproto.Message):
    action: str = betterproto.string_field(1)
    connector: str = betterproto.string_field(2)


@dataclass
class NotSupportedErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "NotSupportedError" = betterproto.message_field(2)


@dataclass
class EmptyFileError(betterproto.Message):
    file: str = betterproto.string_field(1)


@dataclass
class EmptyFileErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "EmptyFileError" = betterproto.message_field(2)


@dataclass
class HyphenDebugger(betterproto.Message):
    pass


@dataclass
class HyphenDebuggerMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "HyphenDebugger" = betterproto.message_field(2)


@dataclass
class ListOfInstalledAdapters(betterproto.Message):
    db_list: str = betterproto.string_field(1)


@dataclass
class ListOfInstalledAdaptersMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ListOfInstalledAdapters" = betterproto.message_field(2)


@dataclass
class ConfigurationFileNotFound(betterproto.Message):
    file: str = betterproto.string_field(1)


@dataclass
class ConfigurationFileNotFoundMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ConfigurationFileNotFound" = betterproto.message_field(2)


@dataclass
class SkipExecution(betterproto.Message):
    filename: str = betterproto.string_field(1)


@dataclass
class SkipExecutionMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SkipExecution" = betterproto.message_field(2)


@dataclass
class SummaryReport(betterproto.Message):
    node_name: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)
    info_message: str = betterproto.string_field(3)
    failures: bool = betterproto.bool_field(4)
    starting_time: str = betterproto.string_field(5)
    ending_time: str = betterproto.string_field(6)
    sequence_num: int = betterproto.int32_field(7)
    end_status: str = betterproto.string_field(8)
    total_count: int = betterproto.int32_field(9)


@dataclass
class SummaryReportMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SummaryReport" = betterproto.message_field(2)


@dataclass
class EndSummaryReportCounts(betterproto.Message):
    pass_count: int = betterproto.int32_field(1)
    warn_count: int = betterproto.int32_field(2)
    error_count: int = betterproto.int32_field(3)
    skip_count: int = betterproto.int32_field(4)
    total_count: int = betterproto.int32_field(5)


@dataclass
class EndSummaryReportCountsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SkipExecution" = betterproto.message_field(2)


@dataclass
class ProjectAlreadyExistsInProfile(betterproto.Message):
    project_name: str = betterproto.string_field(1)
    profile_name: str = betterproto.string_field(2)


@dataclass
class ProjectAlreadyExistsInProfileMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ProjectAlreadyExistsInProfile" = betterproto.message_field(2)


@dataclass
class ProjectAlreadyExistsOrNoPermission(betterproto.Message):
    project_name: str = betterproto.string_field(1)
    project_path: str = betterproto.string_field(2)


@dataclass
class ProjectAlreadyExistsOrNoPermissionMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ProjectAlreadyExistsOrNoPermission" = betterproto.message_field(2)


@dataclass
class SeedReport(betterproto.Message):
    seed_path: str = betterproto.string_field(1)
    schema_name: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)


@dataclass
class SeedReportMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SeedReport" = betterproto.message_field(2)


@dataclass
class SnapshotReport(betterproto.Message):
    source_table: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)
    unique_key: str = betterproto.string_field(3)


@dataclass
class SnapshotReportMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SnapshotReport" = betterproto.message_field(2)


@dataclass
class SeedExecutionError(betterproto.Message):
    file_name: str = betterproto.string_field(1)
    err: str = betterproto.string_field(2)


@dataclass
class SeedExecutionErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SeedExecutionError" = betterproto.message_field(2)


@dataclass
class BulkExecuteError(betterproto.Message):
    query: str = betterproto.string_field(1)
    err: str = betterproto.string_field(2)


@dataclass
class BulkExecuteErrorMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "BulkExecuteError" = betterproto.message_field(2)


@dataclass
class CronJobScheduled(betterproto.Message):
    task_type: str = betterproto.string_field(1)
    task_id: int = betterproto.string_field(2)
    cron_data: str = betterproto.string_field(3)

@dataclass
class CronJobScheduledMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "CronJobScheduled" = betterproto.message_field(2)

@dataclass
class UpdateCronJob(betterproto.Message):
    task_type: str = betterproto.string_field(1)
    task_id: int = betterproto.string_field(2)
    cron_data: str = betterproto.string_field(3)

@dataclass
class UpdateCronJobMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "UpdateCronJobMsg" = betterproto.message_field(2)

@dataclass
class UpdateFailedCronJob(betterproto.Message):
    task_type: str = betterproto.string_field(1)
    task_id: int = betterproto.string_field(2)
    cron_data: str = betterproto.string_field(3)

@dataclass
class UpdateFailedCronJobMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "UpdateFailedCronJob" = betterproto.message_field(2)

@dataclass
class InitiateScheduling(betterproto.Message):
    task_type: str = betterproto.string_field(1)
    cron_data: str = betterproto.string_field(2)

@dataclass
class InitiateSchedulingMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "InitiateScheduling" = betterproto.message_field(2)

@dataclass
class ListScheduledJobs(betterproto.Message):
    tasks: str = betterproto.string_field(1)

@dataclass
class ListScheduledJobsMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ListScheduledJobs" = betterproto.message_field(2)

@dataclass
class DeleteScheduledJob(betterproto.Message):
    task_id: int = betterproto.string_field(1)

@dataclass
class DeleteScheduledJobMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "DeleteScheduledJob" = betterproto.message_field(2)

@dataclass
class FailedDeleteScheduledJob(betterproto.Message):
    task_id: int = betterproto.int32_field(1)

@dataclass
class FailedDeleteScheduledJobMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FailedDeleteScheduledJob" = betterproto.message_field(2)

@dataclass
class FailedScheduleJob(betterproto.Message):
    project_id: str = betterproto.string_field(1)

@dataclass
class FailedScheduleJobMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FailedScheduleJob" = betterproto.message_field(2)


@dataclass
class ModelRunStarted(betterproto.Message):
    model_name: str = betterproto.string_field(1)
    source_table: str = betterproto.string_field(2)
    destination_table: str = betterproto.string_field(3)
    materialization: str = betterproto.string_field(4)

@dataclass
class ModelRunStartedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ModelRunStarted" = betterproto.message_field(2)

@dataclass
class ModelRunSucceeded(betterproto.Message):
    model_name: str = betterproto.string_field(1)
    duration_seconds: float = betterproto.float_field(2)

@dataclass
class ModelRunSucceededMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ModelRunSucceeded" = betterproto.message_field(2)

@dataclass
class ModelRunFailed(betterproto.Message):
    model_name: str = betterproto.string_field(1)
    error: str = betterproto.string_field(2)

@dataclass
class ModelRunFailedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ModelRunFailed" = betterproto.message_field(2)

@dataclass
class TransformationApplied(betterproto.Message):
    model_name: str = betterproto.string_field(1)
    transformation_type: str = betterproto.string_field(2)

@dataclass
class TransformationAppliedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "TransformationApplied" = betterproto.message_field(2)

@dataclass
class TransformationDeleted(betterproto.Message):
    model_name: str = betterproto.string_field(1)
    transformation_type: str = betterproto.string_field(2)

@dataclass
class TransformationDeletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "TransformationDeleted" = betterproto.message_field(2)

@dataclass
class ModelConfigured(betterproto.Message):
    model_name: str = betterproto.string_field(1)
    source: str = betterproto.string_field(2)
    destination: str = betterproto.string_field(3)

@dataclass
class ModelConfiguredMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ModelConfigured" = betterproto.message_field(2)

@dataclass
class SeedCompleted(betterproto.Message):
    seed_name: str = betterproto.string_field(1)
    schema_name: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)

@dataclass
class SeedCompletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "SeedCompleted" = betterproto.message_field(2)

@dataclass
class JobCreated(betterproto.Message):
    job_name: str = betterproto.string_field(1)
    environment_name: str = betterproto.string_field(2)

@dataclass
class JobCreatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "JobCreated" = betterproto.message_field(2)

@dataclass
class JobUpdated(betterproto.Message):
    job_name: str = betterproto.string_field(1)

@dataclass
class JobUpdatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "JobUpdated" = betterproto.message_field(2)

@dataclass
class JobDeleted(betterproto.Message):
    job_name: str = betterproto.string_field(1)

@dataclass
class JobDeletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "JobDeleted" = betterproto.message_field(2)

@dataclass
class JobTriggered(betterproto.Message):
    job_name: str = betterproto.string_field(1)
    scope: str = betterproto.string_field(2)

@dataclass
class JobTriggeredMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "JobTriggered" = betterproto.message_field(2)

@dataclass
class ModelCreated(betterproto.Message):
    model_name: str = betterproto.string_field(1)

@dataclass
class ModelCreatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ModelCreated" = betterproto.message_field(2)

@dataclass
class FileDeleted(betterproto.Message):
    file_names: str = betterproto.string_field(1)

@dataclass
class FileDeletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FileDeleted" = betterproto.message_field(2)

@dataclass
class FileRenamed(betterproto.Message):
    old_name: str = betterproto.string_field(1)
    new_name: str = betterproto.string_field(2)

@dataclass
class FileRenamedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "FileRenamed" = betterproto.message_field(2)

@dataclass
class ConnectionCreated(betterproto.Message):
    connection_name: str = betterproto.string_field(1)
    datasource: str = betterproto.string_field(2)

@dataclass
class ConnectionCreatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ConnectionCreated" = betterproto.message_field(2)

@dataclass
class ConnectionTested(betterproto.Message):
    datasource: str = betterproto.string_field(1)
    result: str = betterproto.string_field(2)

@dataclass
class ConnectionTestedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ConnectionTested" = betterproto.message_field(2)

@dataclass
class ConnectionDeletedEvt(betterproto.Message):
    connection_name: str = betterproto.string_field(1)

@dataclass
class ConnectionDeletedEvtMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ConnectionDeletedEvt" = betterproto.message_field(2)

@dataclass
class EnvironmentCreated(betterproto.Message):
    environment_name: str = betterproto.string_field(1)

@dataclass
class EnvironmentCreatedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "EnvironmentCreated" = betterproto.message_field(2)

@dataclass
class EnvironmentDeleted(betterproto.Message):
    environment_name: str = betterproto.string_field(1)

@dataclass
class EnvironmentDeletedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "EnvironmentDeleted" = betterproto.message_field(2)

@dataclass
class ConnectionDeleteFailed(betterproto.Message):
    connection_name: str = betterproto.string_field(1)
    reason: str = betterproto.string_field(2)

@dataclass
class ConnectionDeleteFailedMsg(betterproto.Message):
    info: "EventInfo" = betterproto.message_field(1)
    data: "ConnectionDeleteFailed" = betterproto.message_field(2)
