from django.urls import path

from backend.core.routers.version_history.views import (
    check_conflicts,
    commit_from_draft,
    commit_project,
    compare_versions,
    discard_draft,
    execute_version,
    finalize_conflict_resolutions,
    get_audit_events,
    get_conflicts,
    get_draft,
    get_current_version,
    get_draft_status,
    get_version_by_id,
    get_version_detail,
    get_version_history,
    list_user_drafts,
    preview_pending_changes,
    preview_resolution,
    preview_rollback,
    resolve_single_conflict,
    retry_git_sync,
    rollback_to_version,
    validate_draft,
    validate_rollback,
    verify_version_integrity,
)

urlpatterns = [
    # Project-level versioning
    path("/commit", commit_project, name="commit-project-version"),
    path("/pending-changes", preview_pending_changes, name="preview-pending-changes"),
    path("/versions", get_version_history, name="get-version-history"),
    path("/compare", compare_versions, name="compare-versions"),
    path("/rollback", rollback_to_version, name="rollback-version"),
    path("/rollback/validate", validate_rollback, name="validate-rollback"),
    path("/rollback/preview", preview_rollback, name="preview-rollback"),
    path("/execute-version", execute_version, name="execute-version"),
    path("/retry-git-sync", retry_git_sync, name="retry-git-sync"),
    path("/drafts", list_user_drafts, name="list-user-drafts"),
    path("/current", get_current_version, name="get-current-version"),
    path("/draft-status", get_draft_status, name="get-draft-status"),
    path("/audit", get_audit_events, name="get-audit-events"),
    path("/version/<int:version_number>", get_version_detail, name="get-version-detail"),
    path("/version/<int:version_number>/verify", verify_version_integrity, name="verify-version-integrity"),
    path("/version-id/<str:version_id>", get_version_by_id, name="get-version-by-id"),
    # Model-scoped (draft/conflict) endpoints
    path("/<str:model_name>/draft", get_draft, name="get-draft"),
    path("/<str:model_name>/draft/discard", discard_draft, name="discard-draft"),
    path("/<str:model_name>/commit-draft", commit_from_draft, name="commit-from-draft"),
    path("/<str:model_name>/conflicts/check", check_conflicts, name="check-conflicts"),
    path("/<str:model_name>/conflicts", get_conflicts, name="get-conflicts"),
    path("/<str:model_name>/conflicts/resolve", resolve_single_conflict, name="resolve-conflict"),
    path("/<str:model_name>/conflicts/finalize", finalize_conflict_resolutions, name="finalize-resolutions"),
    path("/<str:model_name>/conflicts/preview", preview_resolution, name="preview-resolution"),
    path("/<str:model_name>/draft/validate", validate_draft, name="validate-draft"),
]
