"""Git PR workflow service.

Creates feature branches and pull requests for version commits.
Split into push_version_to_branch() and create_pr_for_version()
so manual mode can push without auto-creating a PR.
"""

import logging
import re
from typing import Any

from backend.core.models.git_repo_config import GitRepoConfig
from backend.core.models.model_version import ModelVersion
from backend.core.models.project_details import ProjectDetails
from backend.core.services.git_service import get_git_service
from backend.core.services.yaml_serializer import (
    build_git_version_folder_path,
    serialize_model_to_yaml,
)
from backend.errors.exceptions import (
    GitBranchAlreadyExistsException,
    GitPRAlreadyExistsException,
    GitPRException,
)

logger = logging.getLogger(__name__)


def _sanitize_branch_name(name: str) -> str:
    sanitized = name.lower().strip()
    sanitized = re.sub(r"[^a-z0-9/_-]", "-", sanitized)
    sanitized = re.sub(r"-+", "-", sanitized)
    sanitized = sanitized.strip("-")
    return sanitized[:100]


def _build_branch_name(config: GitRepoConfig, project: ProjectDetails, version: ModelVersion) -> str:
    prefix = config.pr_branch_prefix or "visitran/"
    project_slug = _sanitize_branch_name(project.project_name)
    return f"{prefix}{project_slug}/v{version.version_number}"


def _build_pr_body(version: ModelVersion, project: ProjectDetails) -> str:
    model_data = version.model_data or {}
    model_names = sorted(model_data.keys())
    model_list = "\n".join(f"- {name}" for name in model_names) or "- (none)"
    return (
        f"## Visitran Version {version.version_number}\n\n"
        f"**Project:** {project.project_name}\n"
        f"**Commit message:** {version.commit_message or '(no message)'}\n"
        f"**Models ({len(model_names)}):**\n{model_list}\n\n"
        f"---\n"
        f"*Auto-generated by Visitran version control.*"
    )


def _get_service_for_branch(git_config: GitRepoConfig, branch: str):
    """Create a git service instance targeting a specific branch."""
    from backend.core.services.git_service import GitHubService, GitLabService
    credentials = git_config.decrypted_credentials or {}
    token = credentials.get("token", "")
    repo_url = git_config.repo_url or ""
    if "github.com" in repo_url:
        return GitHubService(repo_url, token, branch)
    return GitLabService(repo_url, token, branch)


def push_version_to_branch(
    project_instance: ProjectDetails,
    version: ModelVersion,
    git_config: GitRepoConfig,
) -> dict[str, Any]:
    """Create branch and push YAML files. Does NOT create a PR.

    Returns { branch_name, commit_sha }.
    """
    from django.utils import timezone as dj_timezone

    branch_name = _build_branch_name(git_config, project_instance, version)
    base_branch = git_config.pr_base_branch or git_config.branch_name or "main"

    base_service = _get_service_for_branch(git_config, base_branch)

    # 1. Create feature branch
    try:
        base_service.create_branch(branch_name, from_branch=base_branch)
        logger.info("Created branch %s from %s", branch_name, base_branch)
    except GitBranchAlreadyExistsException:
        logger.info("Branch %s already exists — reusing", branch_name)

    # 2. Push YAML files to feature branch
    feature_service = _get_service_for_branch(git_config, branch_name)
    project_name = project_instance.project_name or ""
    org_id = str(project_instance.organization_id) if project_instance.organization_id else ""
    model_data = version.model_data or {}
    last_commit_sha = ""

    for model_name, single_model_data in model_data.items():
        yaml_content = serialize_model_to_yaml(
            model_data=single_model_data, model_name=model_name,
            project_name=project_name, version_number=version.version_number,
        )
        file_path = build_git_version_folder_path(
            config=git_config, project_name=project_name,
            version_number=version.version_number,
            commit_message=version.commit_message,
            model_name=model_name, org_id=org_id,
        )
        _existing, existing_sha = feature_service.get_file(file_path)
        git_msg = (
            f"v{version.version_number}: {version.commit_message}"
            if version.commit_message
            else f"v{version.version_number}: {model_name}"
        )
        result = feature_service.put_file(
            path=file_path, content=yaml_content, message=git_msg, sha=existing_sha,
        )
        last_commit_sha = result.get("commit_sha", "")

    # 3. Update version tracking fields
    version.git_sync_status = "synced"
    version.git_commit_sha = last_commit_sha[:40]
    version.git_branch_name = branch_name
    version.save(update_fields=["git_sync_status", "git_commit_sha", "git_branch_name"])

    git_config.connection_status = "connected"
    git_config.last_synced_at = dj_timezone.now()
    git_config.error_message = ""
    git_config.save(update_fields=["connection_status", "last_synced_at", "error_message"])

    logger.info("Push to branch complete: %s (commit=%s)", branch_name, last_commit_sha[:8] if last_commit_sha else "?")
    return {"branch_name": branch_name, "commit_sha": last_commit_sha}


def create_pr_for_version(
    project_instance: ProjectDetails,
    version: ModelVersion,
    git_config: GitRepoConfig,
) -> dict[str, Any]:
    """Create a PR for a version that has already been pushed to a branch.

    Returns { pr_number, pr_url }.
    """
    if not version.git_branch_name:
        raise GitPRException(error_message="Version has not been pushed to a branch yet.")

    base_branch = git_config.pr_base_branch or git_config.branch_name or "main"
    base_service = _get_service_for_branch(git_config, base_branch)

    pr_title = (
        f"v{version.version_number}: {version.commit_message}"
        if version.commit_message
        else f"v{version.version_number}: Version snapshot"
    )
    pr_body = _build_pr_body(version, project_instance)

    try:
        pr_result = base_service.create_pull_request(
            title=pr_title, body=pr_body,
            head_branch=version.git_branch_name, base_branch=base_branch,
        )
    except GitPRAlreadyExistsException:
        logger.info("PR already exists for %s -> %s", version.git_branch_name, base_branch)
        pr_result = {"pr_number": version.pr_number, "pr_url": version.pr_url or "", "title": pr_title, "state": "existing"}

    version.pr_number = pr_result.get("pr_number")
    version.pr_url = pr_result.get("pr_url", "")
    version.save(update_fields=["pr_number", "pr_url"])

    logger.info("PR created: #%s for branch %s", pr_result.get("pr_number", "?"), version.git_branch_name)
    return {"pr_number": pr_result.get("pr_number"), "pr_url": pr_result.get("pr_url", "")}


def commit_version_to_branch(
    project_instance: ProjectDetails,
    version: ModelVersion,
    git_config: GitRepoConfig,
    commit_message: str = "",
) -> dict[str, Any]:
    """Convenience wrapper: push to branch + create PR (auto mode)."""
    push_result = push_version_to_branch(project_instance, version, git_config)
    pr_result = create_pr_for_version(project_instance, version, git_config)
    return {**push_result, **pr_result}
