"""Git PR workflow service.

Creates pull requests from the working branch to the base branch.
All commits are pushed to config.branch_name (working branch) by the
auto-commit / manual-commit celery tasks. This service just creates PRs.
"""

import logging
from typing import Any

from backend.core.models.git_repo_config import GitRepoConfig
from backend.core.models.model_version import ModelVersion
from backend.core.models.project_details import ProjectDetails
from backend.core.services.git_service import get_git_service
from backend.errors.exceptions import (
    GitPRAlreadyExistsException,
    GitPRException,
)

logger = logging.getLogger(__name__)


def _build_pr_body(version: ModelVersion, project: ProjectDetails) -> str:
    model_data = version.model_data or {}
    model_names = sorted(model_data.keys())
    model_list = "\n".join(f"- {name}" for name in model_names) or "- (none)"
    return (
        f"## Visitran Version {version.version_number}\n\n"
        f"**Project:** {project.project_name}\n"
        f"**Commit message:** {version.commit_message or '(no message)'}\n"
        f"**Models ({len(model_names)}):**\n{model_list}\n\n"
        f"---\n"
        f"*Auto-generated by Visitran version control.*"
    )


def create_pr_for_version(
    project_instance: ProjectDetails,
    version: ModelVersion,
    git_config: GitRepoConfig,
) -> dict[str, Any]:
    """Create a PR from the working branch to the base branch.

    Working branch = git_config.branch_name (where commits are pushed).
    Base branch = git_config.pr_base_branch (merge target).

    If a PR already exists for this head→base, returns the existing PR info.
    Returns { pr_number, pr_url }.
    """
    head_branch = git_config.branch_name or "main"
    base_branch = git_config.pr_base_branch or "main"

    if head_branch == base_branch:
        raise GitPRException(
            error_message=f"Working branch and base branch are the same ({head_branch}). "
            f"Configure a different working branch or base branch to use PR workflow."
        )

    service = get_git_service(git_config)

    pr_title = (
        f"v{version.version_number}: {version.commit_message}"
        if version.commit_message
        else f"v{version.version_number}: Version snapshot"
    )
    pr_body = _build_pr_body(version, project_instance)

    try:
        pr_result = service.create_pull_request(
            title=pr_title, body=pr_body,
            head_branch=head_branch, base_branch=base_branch,
        )
    except GitPRAlreadyExistsException:
        logger.info("PR already exists for %s -> %s", head_branch, base_branch)
        # Return existing PR info from the version if available
        if version.pr_number:
            return {"pr_number": version.pr_number, "pr_url": version.pr_url or ""}
        # Re-raise so caller can handle (409 response)
        raise

    version.pr_number = pr_result.get("pr_number")
    version.pr_url = pr_result.get("pr_url", "")
    version.save(update_fields=["pr_number", "pr_url"])

    logger.info(
        "PR created: #%s (%s -> %s)",
        pr_result.get("pr_number", "?"), head_branch, base_branch,
    )
    return {
        "pr_number": pr_result.get("pr_number"),
        "pr_url": pr_result.get("pr_url", ""),
    }
