"""YAML serialization utilities for git-backed version control.

Provides deterministic YAML output (sorted keys) to minimize
git diffs, plus file path construction for repo layouts.
"""

import logging
import re
from datetime import datetime, timezone
from typing import Any

import yaml

logger = logging.getLogger(__name__)


def serialize_model_to_yaml(
    model_data: dict[str, Any],
    model_name: str,
    project_name: str,
    version_number: int,
) -> str:
    """Convert model data to deterministic YAML with a metadata header."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = (
        f"# Visitran Model Version\n"
        f"# Model: {model_name}\n"
        f"# Project: {project_name}\n"
        f"# Version: {version_number}\n"
        f"# Generated: {timestamp}\n"
        f"# WARNING: This file is auto-generated by Visitran.\n"
        f"#          Manual edits may be overwritten on next commit.\n"
        f"---\n"
    )
    body = yaml.dump(
        model_data, default_flow_style=False, sort_keys=True,
        allow_unicode=True, indent=2, width=120,
    )
    return header + body


def build_git_file_path(
    config: Any, model_name: str, org_id: str, project_id: str,
) -> str:
    """Build the file path for a model's YAML in the git repository."""
    base = (config.base_path or "").strip("/")
    if config.repo_type == "default":
        segments = [base, org_id, project_id, f"{model_name}.yaml"]
    else:
        segments = [base, f"{model_name}.yaml"]
    return "/".join(s for s in segments if s)


def _sanitize_commit_message(msg: str) -> str:
    sanitized = msg.lower().strip()
    sanitized = re.sub(r"[^a-z0-9]", "_", sanitized)
    sanitized = re.sub(r"_+", "_", sanitized)
    sanitized = sanitized.strip("_")
    return sanitized[:50]


def build_git_version_folder_path(
    config: Any,
    project_name: str,
    version_number: int,
    commit_message: str,
    model_name: str,
    org_id: str,
) -> str:
    """Build the file path for a model YAML inside a version folder."""
    base = (config.base_path or "").strip("/")
    sanitized_msg = _sanitize_commit_message(commit_message) if commit_message else ""
    version_folder = f"v{version_number}"
    if sanitized_msg:
        version_folder = f"v{version_number}_{sanitized_msg}"
    safe_project = re.sub(r"[^a-zA-Z0-9_-]", "_", project_name.strip())
    if config.repo_type == "default":
        segments = [base, org_id, safe_project, version_folder, f"{model_name}.yaml"]
    else:
        segments = [base, safe_project, version_folder, f"{model_name}.yaml"]
    return "/".join(s for s in segments if s)
